.rat-excludes and rat check action

diff --git a/.github/workflows/pr-rat-check.yml b/.github/workflows/pr-rat-check.yml
--- a/.github/workflows/pr-rat-check.yml
+++ b/.github/workflows/pr-rat-check.yml
@@ -1,4 +1,4 @@
-###
+#
 # Licensed to the Apache Software Foundation (ASF) under one
 # or more contributor license agreements.  See the NOTICE file
 # distributed with this work for additional information
@@ -15,32 +15,26 @@
 # KIND, either express or implied.  See the License for the
 # specific language governing permissions and limitations
 # under the License.
-###
+#
 
-target/
-/local
+name: Run Apache RAT check
 
-**/.idea
+on:
+  pull_request:
+    types: [opened, synchronize, reopened, ready_for_review]
 
-# Repository wide ignore mac DS_Store files
-.DS_Store
+jobs:
+  apache-rat-check:
+    runs-on: ubuntu-latest
 
-# Eclipse, Netbeans and IntelliJ files
-!.gitignore
-!.github
-/nbproject
-/*.ipr
-/*.iws
-*.iml
-.settings/
-.project
-.classpath
-.factorypath
-.vscode
-.run/
-.checkstyle
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-*.log
+      - name: Download Apache RAT
+        run: |
+          curl -LO https://repo1.maven.org/maven2/org/apache/rat/apache-rat/0.16.1/apache-rat-0.16.1.jar
 
-# Apache RAT check excludes file
-!.rat-excludes
+      - name: Run Apache RAT
+        run: |
+          java -jar apache-rat-0.16.1.jar -d . -E .rat-excludes | grep "== File:" && echo "The files listed above are missing license headers." && exit 1 || echo "All files have license headers."
