apache rat 17

diff --git a/.github/workflows/pr-rat-check.yml b/.github/workflows/pr-rat-check.yml
--- a/.github/workflows/pr-rat-check.yml
+++ b/.github/workflows/pr-rat-check.yml
@@ -33,8 +33,8 @@ jobs:
 
       - name: Download Apache RAT
         run: |
-          curl -LO https://repo1.maven.org/maven2/org/apache/rat/apache-rat/0.16.1/apache-rat-0.16.1.jar
+          curl -LO https://repository.apache.org/content/repositories/snapshots/org/apache/rat/apache-rat/0.17-SNAPSHOT/apache-rat-0.17-20241115.065104-374.jar
 
       - name: Run Apache RAT
         run: |
-          java -jar apache-rat-0.16.1.jar -d . -E .rat-excludes | grep "== File:" && echo "The files listed above are missing license headers." && exit 1 || echo "All files have license headers."
+          java -jar apache-rat-0.17-20241115.065104-374.jar --input-exclude-file .rat-excludes -- . | grep "INFO:   Unapproved:  0" && echo "All files have license headers." || echo "The files listed above are missing license headers." && exit 1
